#!/bin/bash

# prepare environment
module load anaconda3/2021.05
source activate myenv_arbor
#module load python/3.8.10
module load gcc/10.2.0
module load cuda
module load cmake

# set environment variables required to run custom Arbor installation
source set_arbor_env_gpu

# compile the mechanisms and build the catalogue
#rm -R -f ./tmp
#arbor-build-catalogue custom mechanisms --debug "./tmp"
arbor-build-catalogue custom mechanisms

conda deactivate
