#!/bin/bash

module load anaconda3
source activate myenv_arbor_1
#module load python/3.8.10
module load gcc/10.2.0
module load cuda
module load cmake

# set environment variables required to run custom Arbor installation
source set_arbor_env_dev

# compile the mechanisms and build the catalogue
arbor-build-catalogue custom mechanisms

conda deactivate
