#!/bin/bash

# build necessary catalogue (also sets the environment to run custom Arbor installation)
source build_catalogue

# run the simulation with timesteps of 2e-4s
python3 ./arborNetworkConsolidation.py -s_desc="smallnet2 det max. activity, dt=0.2ms" -dt=0.2 -runtime=3 -config_file="config_smallnet2_det.json"

# run the simulation with timesteps of 2e-6s
python3 ./arborNetworkConsolidation.py -s_desc="smallnet2 det max. activity, dt=0.002ms" -dt=0.002 -runtime=3 -config_file="config_smallnet2_det.json"

