#!/bin/bash

# set environment variables required to run custom Arbor installation
source set_arbor_env_dev

# run the simulations
python3 ./arborNetworkConsolidation.py -config_file="config_smallnet2_basic_late.json" -sample_curr=1
