#!/bin/bash

# set environment variables required to run custom Arbor installation
source set_arbor_env_dev

# run the simulations with standard parameters
python3 ./arborNetworkConsolidation.py -runtime=28820 -learn='{"time_start": 10, "scheme": "TRIPLET", "freq": 100, "N_stim": 25}' -recall='{"time_start": 28810, "scheme": "ONEPULSE", "freq": 100, "N_stim": 25}' -s_desc="smallnet3 det, dt=0.2ms, 8h, with recall" -dt=0.2 -config_file="config_smallnet3_det.json" -sample_curr=0
