#!/bin/bash

# set environment variables required to run custom Arbor installation
source set_arbor_env_dev

# run the simulations
python3 ./arborNetworkConsolidation.py -config_file="config_smallnet2_basic_early.json" -output_period=1 -sample_curr=1
python3 ./arborNetworkConsolidation.py -config_file="config_smallnet2_basic_early_recall.json" -output_period=1 -sample_curr=1
python3 ./arborNetworkConsolidation.py -config_file="config_smallnet2_basic_early_det.json" -output_period=1 -sample_curr=1

