#!/bin/bash

# build necessary catalogue (also sets the environment to run custom Arbor installation)
source build_catalogue

# run the simulations with standard parameters
python3.10 ./arborNetworkConsolidation.py -runtime=25 -learn='{"time_start": 10, "scheme": "TRIPLET", "freq": 100, "N_stim": 25}' -recall='{"time_start": 20, "scheme": "ONEPULSE", "freq": 100, "N_stim": 25}' -s_desc="smallnet3 det, dt=0.2ms, 10s, with recall" -dt=0.2 -config_file="config_smallnet3_det.json" -sample_curr=0
